[project]
name = "naturelifecert"
version = "0.0.1"
description = "The certificate generating application for naturelife"
dependencies = [
    "flask",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"